### ISSUE TITLE
Replace React.createClass

### ISSUE THREAD

**Issue by jochenberger** [jquense/uncontrollable#21]
React 15.5 (RC) shows a warning:
`Warning: Uncontrolled(Dropdown): React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

**Comment by jquense** [comment]
PR welcome

**Comment by jochenberger** [comment]
with `extends` or with `create-react-class`?

**Comment by ingro** [comment]
@jochenberger since this library use mixins I guess with `create-react-class`

**Comment by jquense** [comment]
I'd be OK with either but we should probably refactor to use plain classes, to avoid extra  bytes

**Comment by jochenberger** [comment]
Closing in favor of #22
