### ISSUE TITLE
React.createClass is deprecated

### ISSUE THREAD

**Issue by bigkrp** [jquense/uncontrollable#23]
I shoud use create-react-class.

Warning: Uncontrolled(Dropdown): React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by jquense** [comment]
Upgrade to the newest version

**Comment by bigkrp** [comment]
I have version "4.0.3".(It was installed as a dependence of react-bootstrap, i see it lates version)
and warning at 
https://github.com/jquense/uncontrollable/blob/master/lib/createUncontrollable.js#L52

**Comment by jquense** [comment]
react-bootstrap hasn't upgraded it's version yet then
