### ISSUE TITLE
Publish 4.1.0

### ISSUE THREAD

**Issue by wbazant** [jquense/uncontrollable#24]
I came here investigating this error:
```
Warning: Uncontrolled(MyComponent): isMounted is deprecated. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.
```

I think `uncontrollable` is pretty great and I started using it heavily - it lets me standardise how my components keep state unless they need to do something unusual. I see the fix is for the warning I was seeing is already in - will you be publishing another version of the package soon? Do you plan to do something specific before that? I can put forward my time to help.

**Comment by taion** [comment]
4.1.0 has been published, so this should be closed.
