### ISSUE TITLE
Stop using legacy lifecycle methods

### ISSUE THREAD

**Issue by ntucker** [jquense/uncontrollable#32]
```Warning: Unsafe lifecycle methods were found within a strict-mode tree:

componentWillMount: Please update the following components to use componentDidMount instead: Uncontrolled(Component), Uncontrolled(Navbar)

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: Uncontrolled(Component), Uncontrolled(Navbar)
```

https://fb.me/react-strict-mode-warnings

These have been around for quite some time. Using deprecated stuff considered harmful.

**Comment by aaryn101** [comment]
Is there any update to this? I want to use this library but I am concerned about what will happen when we move to React v17.

**Comment by jquense** [comment]
i've not gotten around to updating, but will when it is pressing. in the meantime you can use the hook if you want to avoid the deprecated methods
