### ISSUE TITLE
Multiple handlers for the same property

### ISSUE THREAD

**Issue by andru** [jquense/uncontrollable#4]
Is this possible? I keep finding myself wanting to do things like this...

```
uncontrollable(Component, {isFocused:['onFocus', 'onBlur']}
```

I'm solving it by creating an `onToggleFocus` handler which is called with true `onFocus` and false  `onBlur`, and perhaps that's the best way, but I feel a bit weird about creating a handler which probably wouldn't exist if I wasn't using uncontrollable...

```
uncontrollable(Component, {isFocused:'onToggleFocus'}
```

Any thoughts?

(edit to make the example a bit less contrived)

**Comment by jquense** [comment]
In general I tend to think that one prop to one handler is the right way to go in structuring component apis with or without uncontrollable, but I can see how that's not always the most convenient. To answer the question, it's not possible with the current API, but I might be open

**Comment by andru** [comment]
Yeah I can live with it, I just wanted to see if I was missing an obvious solution.  Adding another handler on the object isn't a big deal.

I'll close this but feel free to reopen if there's anything else to say on the matter.
