### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by thealjey** [jquense/uncontrollable#6]
How do I get a reference to the original component?
this.refs contains an instance of uncontrollable, what I want is to somehow get a hold of a component that it wraps

**Comment by jquense** [comment]
I was going to point you to an undocumented feature, when I realized that it wasn't in the code base! So thanks for inadvertently letting me know about that.

I have fixed and released the missing feature in 3.1.2, you can provide a lsit of methods you want to "just work" (see the readme) or if that doesn't suit your needs you reach in and access the ref like  `this.refs.uncontrolledThing.refs.inner`
