### ISSUE TITLE
propTypes removed from react 15.x

### ISSUE THREAD

**Issue by kromit** [jquense/uncontrollable#9]
'propTypes' prop like in [src/createUncontrollable.js#L10](https://github.com/jquense/uncontrollable/blob/master/src/createUncontrollable.js#L10) can not be used anymore with react 15.x

**Comment by mjw56** [comment]
I tested locally and it looks like #10 fixes the issue. @jquense can this fix be added to react-bootstrap?

**Comment by julien-f** [comment]
Could you please release the fixed code on npm?

**Comment by jquense** [comment]
this is fixed!
